//creates a generator function that will provide day names for a number of days from any given date
function* generateDayNames(startDate, numDays) {
    const dayNames = ["Sunday", "Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday"]
    //for loop to calculate the day names for the number of days
    for (let i=0; i < numDays; i++) {
        const nextDate = new Date(startDate);
        nextDate.setDate(startDate.getDate() + i);
        yield dayNames[nextDate.getDay()];
    }
}

//js provided for practice
const DAYS = 6;
const LIMIT = 30;
let studentReport = [11, 42, 33, 64, 29, 37, 44];

//forloop that iterates through the array and outputs the values below 30
for(let i=0; i < studentReport.length; i++) {
    if (studentReport[i] < LIMIT)  {
        console.log(studentReport[i]);
    }
}

//change to while loop for same functionality
let i =0;
while (i < studentReport.length) {
    if (studentReport[i] < LIMIT) {
        console.log(studentReport[i]);
    }
}

//change to forEach loop for same functionality
studentReport.forEach(function(item) {
    if (item <LIMIT) {
        console.log(item);
    };
});

//creates a Date object and uses a for...of loop to iterate through the day names generated by the generator function making the the functionality more reusable
const today = new Date();
for (const dayName of generateDayNames(today, DAYS)) {
    console.log(dayName);
}
